# Generated by Django 4.1.5 on 2024-01-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('temperature', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
